name: AllMusic
main: coloryr.allmusic.AllMusicBukkit
author: Color_yr
version: 2.14.9
loadbefore: [PlaceholderAPI, Vault, Essentials, CMI]

commands:
  music:
    description: AllMusic
    usage: ยง4[AllMusic]ยง6/music help
